/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "redis_constants.h"

namespace redisproxy {

const redisConstants g_redis_constants;

redisConstants::redisConstants() {
}

} // namespace

