/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef redis_CONSTANTS_H
#define redis_CONSTANTS_H

#include "redis_types.h"

namespace redisproxy {

class redisConstants {
 public:
  redisConstants();

};

extern const redisConstants g_redis_constants;

} // namespace

#endif
